### ISSUE TITLE
Add base documents, products and clients manipulations

### ISSUE THREAD

**Issue by wi1sp** [Porphum/PorphumWeb#23]
**ToDo:**
- [ ] product controller
  - [x] product repository
  - [x] group repository (for managin groups and future add sub-groups logic, maybe in one repository)
- [ ] clients controller
  - [x] clients repository
- [ ] documents controller
  - [ ] documents repository
  - [x] logic for different doc type
  - [x] logic for doc state
